[pipepad]
# Language used for all new pads unless specified otherwise
default_language = "python"
delete_tmp_pad = false

[pipepad.env_vars]
fifo = "PIPEPAD_FIFO"
cur_path = "PIPEPAD_CUR_PATH"
pad_lang = "PIPEPAD_PAD_LANG"


[[repo]]
name = "samples"
path = "./samples/sample_repo"


[[repo]]
name = "samples3"
path = "./samples/sample_repo4"


#[[repo]]
#type = "git"
#name = "pad-registry"
#url = "git://foo/bar"
#
