[pipepad]
# Language used for all new pads unless specified otherwise
default_language = "python"
delete_tmp_pad = false

[pipepad.env_vars]
fifo = "PIPEPAD_FIFO"
cur_path = "PIPEPAD_CUR_PATH"
pad_lang = "PIPEPAD_PAD_LANG"


[[registry]]
name = "local"
path = "foo/bar"


[[registry]]
name = "pad-registry"
url = "git://foo/bar"

